# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XkztfCz7PfwDJbSMRWehRamZ8D-itOJb

**VAC 14**
"""

import numpy as np

n1=247
p1=.37
n2=308
p2=.39

sample1=np.random.binomial(1,p1,n1)

sample1

sample2=np.random.binomial(1,p2,n2)

sample2

len(sample2)

import statsmodels.api as sm
p=sm.stats.ttest_ind(sample1, sample2)
print(p)

#Chi square test  test of independence
from scipy.stats import chi2_contingency
from matplotlib import pyplot as plt
import pandas as pd

data = [[14,4],[0,10]]
data

df=pd.DataFrame(data,
                index=['Athlete','Non-Ahtlete'],columns=['NOn Smoker','Smoker'])
df

df.plot(kind='bar')

chi2_contingency(data)

chi2,p,dof,exp=chi2_contingency(data)
chi2

p

a=0.5
if p<a:
    print('Reject null hypothesis')
else:
    print('Accept null hypothesis')























